nav:
    - Home: index.md
    - Data Intake: intake.md
    - Storage and Structure: storage.md
    - QC and Preprocessing: qc_preproc.md
    - Analysis - Structural: structural.md
    - Analysis - Functional: functional.md
    - Analysis - Diffusion Weighted Imaging: dti.md
    - Misc - Cloud Storage: osf.md

theme: readthedocs